export const ActionTypes = {
  SET_POST: "SET_POST",
  SELECTED_POST: "SELECTED_POST",
  REMOVE_SELECTED_POST: "REMOVE_SELECTED_POST",
  SELECTED_USER: "SELECTED_USER",
  SELECTED_COMMENTS: "SELECTED_COMMENTS",
  SELECTED_ALBUMS: "SELECTED_ALBUMS",
  SELECTED_PHOTO_ALBUMS: "SELECTED_PHOTO_ALBUMS",
  REMOVE_SELECTED_PHOTO_ALBUMS: "REMOVE_SELECTED_PHOTO_ALBUMS",
};
